### ISSUE TITLE
Support specifying replication class and options from cassandra.create call

### ISSUE THREAD

**Issue by bradfordcp** [o19s/trireme#1]

**Comment by HopefulLlama** [comment]
Any preference to how this will be exposed in the configuration?

**Comment by bradfordcp** [comment]
I'm not sure if we want to expose these as parameters to the Invoke task or just as keys in the config file. Currently I'm leaning towards keys in the config file, maybe something like this:

```python
replication_strategy = 'NetworkTopologyStrategy'
replication_options = {'DC1': 1, 'DC2': 2}

# or

replication_strategy = 'SimpleStrategy'
replication_options = {'replication_factor': 2}
```

**Comment by HopefulLlama** [comment]
I would also lean towards the configuration, although in my mind I was thinking something along the lines of: 

`replication = {
    strategy: 'SimpleStrategy',
    factor: 2,
    options: {'DC1': 1, 'DC2': 2}
}`

**Comment by bradfordcp** [comment]
The options change depending on the strategy, thus the generic hash to hold them. Storing everything inside a single variable fits well here and feels like the syntax used in CQL.

**Comment by bradfordcp** [comment]
Version 1.2.0 has been rolled with this change and pushed to PyPI. Thanks!
