### ISSUE TITLE
Support pushing all files under a solr core to DSE solr

### ISSUE THREAD

**Issue by bradfordcp** [o19s/trireme#10]
For example, I may want a stopwords.txt file uploaded along with my core. Currently only the schema.xml and solrconfig.xml file are pushed.

**Comment by epugh** [comment]
Out of curisoty, is any of the "restful" schema stuff used in DSE?   So instead of pushing up a schema.xml file, you end up just creating those fields.    Maybe your migration script could do both C* and Solr at the sam etime...
