### ISSUE TITLE
Writing migration CQL-scripts

### ISSUE THREAD

**Issue by sedovalx** [o19s/trireme#28]
Can you give me a hint how you write scripts for a migration from one schema to another, please? It's offtopic a little bit but I just don't understand how to use this solution without such knowledge. For example, 
* You need to add new table in the next migration. And you should fill it with existing data.
* You should change the type or name of an existsing column

Thanks!

**Comment by bradfordcp** [comment]
1. Moving existing data will need another tool, in the past I've used Spark for this.
1. For altering a table see the [CQL Docs](http://docs.datastax.com/en/cql/3.0/cql/cql_reference/alter_table_r.html). Anything you can do with CQL this tool supports.

**Comment by bradfordcp** [comment]
You can use the `invoke cassandra.add_migration --name foo` command to generate the file where your CQL commands should be placed.

**Comment by sedovalx** [comment]
Ok, I see. What I dont understand is why do you need schema migration without data migration. Can you put some light on it?

**Comment by bradfordcp** [comment]
We would re-ingest data after updating the schema / API. In our use-case there was no need for data migration. That being said data migration is important, but we are limited by the capabilities of CQL. This project was created to handle keeping developer and environment's schemas in sync. We handled the data separately. There is value in migrating data, but depending on the size of your data it will require some tooling outside of the scope of a CQL script. I've personally used Spark for this, but it is possible with other tools.

**Comment by sedovalx** [comment]
Thank you!
