### ISSUE TITLE
Any plans to continue maintaining this repo?

### ISSUE THREAD

**Issue by HopefulLlama** [o19s/trireme#29]
I would like to fork and develop on this, but am wondering if this repository is being maintained?

This is important, as I would like to be able to publish changes made into Pip, whether this be done by you or myself.

I ask this as the last change is a while ago.

**Comment by bradfordcp** [comment]
This repository is still maintained. Work has stalled a little bit based on time, but o19s would be happy to review any contributions and publish them to pip.

**Comment by HopefulLlama** [comment]
That's great. We'll certainly do that. 

Thanks!
